project:
  type: website
  output-dir: docs

website:
  title: "The Skywalker Arena"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/themohitnair
      - icon: instagram
        href: https://instagram.com/the_mohitnair
      - icon: linkedin
        href: https://www.linkedin.com/in/themohitnair/
format:
  html:
    theme: slate
    css: styles.css



